import * as React from "react";
import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Text,
  Hr,
} from "@react-email/components";
import { Tailwind } from "@react-email/tailwind";
import { brand } from "./components/Brand";
import { Card } from "./components/Card";

type Payload = {
  name: string;
  company?: string;
  email: string;
  phone?: string;
  message?: string;
  // Add more fields if your form has them
};

export default function AdminNotification(p: Payload) {
  return (
    <Html>
      <Head />
      <Preview>New website inquiry from {p.name}</Preview>
      <Tailwind
        config={{
          theme: { extend: { colors: { ...brand.colors } } },
        }}
      >
        <Body className="bg-bg text-text">
          <Container className="mx-auto my-6 w-[600px] rounded-2xl">
            <Text className="text-xl font-semibold">New Inquiry</Text>
            <Card>
              <table style={{ width: "100%", fontSize: 14 }}>
                <tbody>
                  <tr>
                    <td style={{ color: brand.colors.muted, width: 120 }}>
                      Nama
                    </td>
                    <td>{p.name}</td>
                  </tr>
                  {p.company && (
                    <tr>
                      <td style={{ color: brand.colors.muted }}>Perusahaan</td>
                      <td>{p.company}</td>
                    </tr>
                  )}
                  <tr>
                    <td style={{ color: brand.colors.muted }}>Email</td>
                    <td>{p.email}</td>
                  </tr>
                  {p.phone && (
                    <tr>
                      <td style={{ color: brand.colors.muted }}>Telepon</td>
                      <td>{p.phone}</td>
                    </tr>
                  )}
                </tbody>
              </table>

              {p.message && (
                <>
                  <Hr className="my-3 border-border" />
                  <Text className="text-sm whitespace-pre-wrap leading-6">
                    {p.message}
                  </Text>
                </>
              )}
            </Card>

            <Hr className="my-5 border-border" />
            <Text className="text-xs text-muted">
              This email was generated by the website contact form.
            </Text>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
}
